<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0e5f4d491dacced86cebb041e6f3a051
{
    public static $files = array (
        '4cdafd4a5191caf078235e7dd119fdaf' => __DIR__ . '/..' . '/flightphp/core/flight/autoload.php',
        'e3cd3e6ea0fe16cf6c6b16fa591c5162' => __DIR__ . '/..' . '/flightphp/core/flight/Flight.php',
    );

    public static $classMap = array (
        'AuthController' => __DIR__ . '/../..' . '/app/controllers/AuthController.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'UserRepository' => __DIR__ . '/../..' . '/app/repositories/UserRepository.php',
        'UserService' => __DIR__ . '/../..' . '/app/services/UserService.php',
        'Validator' => __DIR__ . '/../..' . '/app/services/Validator.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit0e5f4d491dacced86cebb041e6f3a051::$classMap;

        }, null, ClassLoader::class);
    }
}
